#!/usr/bin/env bash

CONFIG=~/.config

if [[ "$(uname)" == "Darwin" ]]; then
    echo "Darwin OS Detected"
fi

if [[ "$(uname)" == "Linux" ]]; then
    if [ -f /etc/os-release ] ; then
        source /etc/os-release
        DIST=$ID
    else
        __ROOT__='/data/data/com.termux/files'
        DIST="termux"
    fi
    echo "Linux OS Detected, DIST = $DIST"
fi

. fresh.bash
fresh --begin
cd ~/.dotfiles

# =====================================================
# Fish shell settings
# run bootstrap-oh-my-fish to install oh-my-fish
fresh 'fish/config/*' --file=$CONFIG'/fish/config.fish'
fresh 'fish/aliases/*' --file=$CONFIG'/fish/aliases.fish'
if [[ "$(uname)" == "Darwin" ]]; then
  fresh 'fish/config.osx/*' --file=$CONFIG'/fish/config.fish'
  fresh 'fish/aliases.osx/*' --file=$CONFIG'/fish/aliases.fish'
fi
if [[ "$(uname)" == "Linux" ]]; then
  fresh 'fish/config.linux/*' --file=$CONFIG'/fish/config.fish'
  fresh 'fish/aliases.linux/*' --file=$CONFIG'/fish/aliases.fish'
fi
fresh 'fish/functions' --file=$CONFIG'/fish/functions/'

fresh --end
